CREATE TABLE IF NOT EXISTS upgrade_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  playerId VARCHAR(64) NOT NULL,
  playerName VARCHAR(255) NOT NULL,
  attributeName VARCHAR(255) NOT NULL,
  upgradeType VARCHAR(50) NOT NULL,
  userId VARCHAR(64) NOT NULL,
  userName VARCHAR(255) NOT NULL,
  team VARCHAR(100) NOT NULL,
  previousValue VARCHAR(50),
  newValue VARCHAR(50),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
